# Generated by Django 3.2.9 on 2021-11-28 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20211125_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todolist.collection'),
        ),
    ]
